name: "SSH & SFTP deploy"
description: "Connect and deploy with ssh and sftp "
author: Jakob Lilliemarck
inputs:
  host:
    description: "Host IP"
    required: true

  username:
    description: "User to connect as"
    required: true

  passphrase:
    description: "SSH key passphrase"
    required: true

  privateKey:
    description: "SSH private key"
    required: true

  files:
    description: "Files to transfer to the host"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
